STL_FILES += $(CURDIR)/parts/structure/carrier_1/c1_carrier.stl

CARRIER_1_DEPS += $(CURDIR)/utils/machining.scad
CARRIER_1_DEPS += $(CURDIR)/utils/structure.scad
CARRIER_1_DEPS += $(CURDIR)/utils/constants/constants.scad
CARRIER_1_DEPS += $(CURDIR)/utils/constants/structure.scad
CARRIER_1_DEPS += $(CURDIR)/utils/constants/moon_to_zodiac/structure.scad
CARRIER_1_DEPS += $(CURDIR)/utils/constants/clock_to_sun/structure.scad
CARRIER_1_DEPS += $(CURDIR)/utils/constants/sun_to_moon/structure.scad
CARRIER_1_DEPS += $(CURDIR)/utils/constants/sun_to_lunar_nodes/structure.scad
CARRIER_1_DEPS += $(CURDIR)/utils/constants/sun_to_lunar_phases/structure.scad
CARRIER_1_DEPS += $(CURDIR)/parts/structure/carrier_1/c1_sector_moon_to_zodiac.module.scad
CARRIER_1_DEPS += $(CURDIR)/parts/structure/carrier_1/c1_sector_sun_to_moon.module.scad
CARRIER_1_DEPS += $(CURDIR)/parts/structure/carrier_1/c1_sector_clock_to_sun.module.scad
CARRIER_1_DEPS += $(CURDIR)/parts/structure/carrier_1/c1_sector_sun_to_lunar_nodes.module.scad
CARRIER_1_DEPS += $(CURDIR)/parts/structure/carrier_1/c1_sector_sun_to_lunar_phases.module.scad
CARRIER_1_DEPS += $(STRUCTURE_DEPS)

$(CURDIR)/parts/structure/carrier_1/c1_carrier.scad: $(CARRIER_1_DEPS)