STL_FILES += $(CURDIR)/parts/structure/carrier_1/c1_carrier.stl

$(CURDIR)/parts/structure/carrier_1/c1_carrier.stl: $(CURDIR)/utils/constants/moon_to_zodiac/structure.scad
$(CURDIR)/parts/structure/carrier_1/c1_carrier.stl: $(CURDIR)/utils/constants/clock_to_sun/structure.scad
$(CURDIR)/parts/structure/carrier_1/c1_carrier.stl: $(CURDIR)/utils/constants/sun_to_moon/structure.scad
$(CURDIR)/parts/structure/carrier_1/c1_carrier.stl: $(CURDIR)/utils/constants/sun_to_lunar_nodes/structure.scad
$(CURDIR)/parts/structure/carrier_1/c1_carrier.stl: $(CURDIR)/utils/constants/sun_to_lunar_phases/structure.scad