PARTS_DEPS := $(CURDIR)/utils/machining.scad

PARTS_SUBDIRS := $(CURDIR)/parts/clock_to_sun $(CURDIR)/parts/moon_to_zodiac $(CURDIR)/parts/motor $(CURDIR)/parts/shafts $(CURDIR)/parts/structure $(CURDIR)/parts/sun_to_lunar_nodes $(CURDIR)/parts/sun_to_lunar_phases $(CURDIR)/parts/sun_to_moon
include $(PARTS_SUBDIRS:%=%/Makefile)
