STL_FILES += $(CURDIR)/parts/structure/carrier_3/c3_carrier.stl

CARRIER_3_DEPS += $(CURDIR)/utils/constants/constants.scad
CARRIER_3_DEPS += $(CURDIR)/utils/constants/structure.scad
CARRIER_3_DEPS += $(CURDIR)/utils/constants/moon_to_zodiac/structure.scad
CARRIER_3_DEPS += $(CURDIR)/utils/constants/clock_to_sun/structure.scad
CARRIER_3_DEPS += $(CURDIR)/utils/constants/sun_to_moon/structure.scad
CARRIER_3_DEPS += $(CURDIR)/utils/constants/sun_to_lunar_nodes/structure.scad
CARRIER_3_DEPS += $(CURDIR)/utils/constants/sun_to_lunar_phases/structure.scad

$(CURDIR)/parts/structure/carrier_3/c3_carrier.scad: $(CARRIER_3_DEPS)