STL_FILES += $(CURDIR)/parts/clock_to_sun/clock_to_sun_gear_1.stl
STL_FILES += $(CURDIR)/parts/clock_to_sun/clock_to_sun_gear_2.stl
STL_FILES += $(CURDIR)/parts/clock_to_sun/clock_to_sun_gear_3.stl
STL_FILES += $(CURDIR)/parts/clock_to_sun/clock_to_sun_gear_4.stl
STL_FILES += $(CURDIR)/parts/clock_to_sun/clock_to_sun_gear_5.stl
STL_FILES += $(CURDIR)/parts/clock_to_sun/clock_to_sun_gear_6a.stl
STL_FILES += $(CURDIR)/parts/clock_to_sun/clock_to_sun_gear_6b.stl
STL_FILES += $(CURDIR)/parts/clock_to_sun/clock_to_sun_gear_7.stl

CLOCK_TO_SUN_DEPS := $(CURDIR)/utils/constants/clock_to_sun/env.scad $(CURDIR)/utils/gear.scad $(PARTS_DEPS)

$(CURDIR)/parts/clock_to_sun/clock_to_sun_gear_1.stl: $(CLOCK_TO_SUN_DEPS)
$(CURDIR)/parts/clock_to_sun/clock_to_sun_gear_2.stl: $(CLOCK_TO_SUN_DEPS)
$(CURDIR)/parts/clock_to_sun/clock_to_sun_gear_3.stl: $(CLOCK_TO_SUN_DEPS)
$(CURDIR)/parts/clock_to_sun/clock_to_sun_gear_4.stl: $(CLOCK_TO_SUN_DEPS)
$(CURDIR)/parts/clock_to_sun/clock_to_sun_gear_5.stl: $(CLOCK_TO_SUN_DEPS)
$(CURDIR)/parts/clock_to_sun/clock_to_sun_gear_6a.stl: $(CLOCK_TO_SUN_DEPS)
$(CURDIR)/parts/clock_to_sun/clock_to_sun_gear_6b.stl: $(CLOCK_TO_SUN_DEPS)
$(CURDIR)/parts/clock_to_sun/clock_to_sun_gear_7.stl: $(CLOCK_TO_SUN_DEPS)
