STL_FILES += $(CURDIR)/parts/structure/misc/c1_c2.stl
STL_FILES += $(CURDIR)/parts/structure/misc/c2_c3.stl
STL_FILES += $(CURDIR)/parts/structure/misc/clamp.stl
STL_FILES += $(CURDIR)/parts/structure/misc/support.stl

$(CURDIR)/parts/structure/misc/c1_c2.stl: $(CURDIR)/utils/constants/structure.scad
$(CURDIR)/parts/structure/misc/c2_c3.stl: $(CURDIR)/utils/constants/structure.scad
$(CURDIR)/parts/structure/misc/clamp.stl: $(CURDIR)/utils/constants/structure.scad
$(CURDIR)/parts/structure/misc/support.stl: $(CURDIR)/utils/constants/structure.scad