STL_FILES += $(CURDIR)/parts/sun_to_lunar_nodes/sun_to_lunar_nodes_gear_1.stl
STL_FILES += $(CURDIR)/parts/sun_to_lunar_nodes/sun_to_lunar_nodes_gear_2.stl
STL_FILES += $(CURDIR)/parts/sun_to_lunar_nodes/sun_to_lunar_nodes_gear_3.stl

SUN_TO_LUNAR_NODES_DEPS = $(CURDIR)/utils/constants/sun_to_lunar_nodes/env.scad $(CURDIR)/utils/gear.scad $(PARTS_DEPS)

$(CURDIR)/parts/sun_to_lunar_nodes/sun_to_lunar_nodes_gear_1.stl: $(SUN_TO_LUNAR_NODES_DEPS)
$(CURDIR)/parts/sun_to_lunar_nodes/sun_to_lunar_nodes_gear_2.stl: $(SUN_TO_LUNAR_NODES_DEPS)
$(CURDIR)/parts/sun_to_lunar_nodes/sun_to_lunar_nodes_gear_3.stl: $(SUN_TO_LUNAR_NODES_DEPS)
