STL_FILES += $(CURDIR)/parts/sun_to_moon/sun_to_moon_gear_1.stl
STL_FILES += $(CURDIR)/parts/sun_to_moon/sun_to_moon_gear_2.stl
STL_FILES += $(CURDIR)/parts/sun_to_moon/sun_to_moon_gear_3.stl
STL_FILES += $(CURDIR)/parts/sun_to_moon/sun_to_moon_gear_4.stl

SUN_TO_MOON_DEPS = $(CURDIR)/utils/constants/sun_to_moon/env.scad $(CURDIR)/utils/gear.scad $(PARTS_DEPS)

$(CURDIR)/parts/sun_to_moon/sun_to_moon_gear_1.stl: $(SUN_TO_MOON_DEPS)
$(CURDIR)/parts/sun_to_moon/sun_to_moon_gear_2.stl: $(SUN_TO_MOON_DEPS)
$(CURDIR)/parts/sun_to_moon/sun_to_moon_gear_3.stl: $(SUN_TO_MOON_DEPS)
$(CURDIR)/parts/sun_to_moon/sun_to_moon_gear_4.stl: $(SUN_TO_MOON_DEPS)
