STRUCTURE_DEPS := $(PARTS_DEPS) $(CURDIR)/utils/structure.scad $(CURDIR)/utils/constants/structure.scad

STRUCTURE_SUBDIRS := $(CURDIR)/parts/structure/carrier_1 $(CURDIR)/parts/structure/carrier_2 $(CURDIR)/parts/structure/carrier_3 $(CURDIR)/parts/structure/spacers
include $(STRUCTURE_SUBDIRS:%=%/Makefile)
