STL_FILES += $(CURDIR)/parts/shafts/clock_internal_shaft.stl
STL_FILES += $(CURDIR)/parts/shafts/lunar_nodes_shaft.stl
STL_FILES += $(CURDIR)/parts/shafts/lunar_phases_shaft.stl
STL_FILES += $(CURDIR)/parts/shafts/moon_internal_shaft.stl
STL_FILES += $(CURDIR)/parts/shafts/moon_shaft.stl
STL_FILES += $(CURDIR)/parts/shafts/sun_shaft.stl
STL_FILES += $(CURDIR)/parts/shafts/zodiac_shaft.stl

$(CURDIR)/parts/shafts/clock_internal_shaft.stl: $(CURDIR)/utils/constants/sun_to_moon/env.scad $(PARTS_DEPS)
$(CURDIR)/parts/shafts/lunar_nodes_shaft.stl: $(CURDIR)/utils/constants/sun_to_lunar_nodes/env.scad $(PARTS_DEPS)
$(CURDIR)/parts/shafts/lunar_phases_shaft.stl: $(CURDIR)/utils/constants/sun_to_lunar_phases/env.scad $(PARTS_DEPS)
$(CURDIR)/parts/shafts/moon_internal_shaft.stl: $(CURDIR)/utils/constants/sun_to_moon/env.scad $(PARTS_DEPS)
$(CURDIR)/parts/shafts/moon_shaft.stl: $(CURDIR)/utils/constants/sun_to_moon/env.scad $(PARTS_DEPS)
$(CURDIR)/parts/shafts/sun_shaft.stl: $(CURDIR)/utils/constants/clock_to_sun/env.scad $(PARTS_DEPS)
$(CURDIR)/parts/shafts/zodiac_shaft.stl: $(CURDIR)/utils/constants/moon_to_zodiac/env.scad $(PARTS_DEPS)