STL_FILES += $(CURDIR)/parts/shafts/lunar_nodes_shaft.stl
STL_FILES += $(CURDIR)/parts/shafts/lunar_phases_shaft.stl
STL_FILES += $(CURDIR)/parts/shafts/moon_shaft.stl
STL_FILES += $(CURDIR)/parts/shafts/sun_shaft.stl
STL_FILES += $(CURDIR)/parts/shafts/zodiac_shaft.stl
STL_FILES += $(CURDIR)/parts/shafts/clock_to_sun_shaft.stl

$(CURDIR)/parts/shafts/lunar_phases_shaft.stl: $(CURDIR)/utils/constants/sun_to_lunar_phases/structure.scad