STL_FILES += $(CURDIR)/parts/motor/motor_case.stl
STL_FILES += $(CURDIR)/parts/motor/motor_cap.stl

$(CURDIR)/parts/motor/motor_case.stl: $(CURDIR)/utils/constants/structure.scad
$(CURDIR)/parts/motor/motor_cap.stl: $(CURDIR)/utils/constants/structure.scad
