STL_FILES += $(CURDIR)/parts/structure/carrier_2/c2_carrier_1.stl
STL_FILES += $(CURDIR)/parts/structure/carrier_2/c2_carrier_2.stl

$(CURDIR)/parts/structure/carrier_2/c2_carrier.stl: $(CURDIR)/utils/constants/moon_to_zodiac/structure.scad
$(CURDIR)/parts/structure/carrier_2/c2_carrier.stl: $(CURDIR)/utils/constants/clock_to_sun/structure.scad
$(CURDIR)/parts/structure/carrier_2/c2_carrier.stl: $(CURDIR)/utils/constants/sun_to_moon/structure.scad
$(CURDIR)/parts/structure/carrier_2/c2_carrier.stl: $(CURDIR)/utils/constants/sun_to_lunar_nodes/structure.scad
$(CURDIR)/parts/structure/carrier_2/c2_carrier.stl: $(CURDIR)/utils/constants/sun_to_lunar_phases/structure.scad