STL_FILES += $(CURDIR)/parts/structure/spacers/c1_c2.stl
STL_FILES += $(CURDIR)/parts/structure/spacers/c2_c3.stl
STL_FILES += $(CURDIR)/parts/structure/spacers/clamp.stl

$(CURDIR)/parts/structure/spacers/c1_c2.stl: $(CURDIR)/utils/constants/structure.scad
$(CURDIR)/parts/structure/spacers/c2_c3.stl: $(CURDIR)/utils/constants/structure.scad
$(CURDIR)/parts/structure/spacers/clamp.stl: $(CURDIR)/utils/constants/structure.scad