STL_FILES += $(CURDIR)/parts/structure/spacers/c1_c2.stl
STL_FILES += $(CURDIR)/parts/structure/spacers/c2_c3.stl
STL_FILES += $(CURDIR)/parts/structure/spacers/clamp.stl

SPACERS_DEPS = $(STRUCTURE_DEPS)

$(CURDIR)/parts/structure/spacers/c1_c2.stl: $(SPACERS_DEPS)
$(CURDIR)/parts/structure/spacers/c2_c".stl: $(SPACERS_DEPS)
$(CURDIR)/parts/structure/spacers/clamp.stl: $(SPACERS_DEPS)