STL_FILES += $(CURDIR)/parts/sun_to_lunar_phases/sun_to_lunar_phases_gear_1.stl
STL_FILES += $(CURDIR)/parts/sun_to_lunar_phases/sun_to_lunar_phases_gear_2.stl
STL_FILES += $(CURDIR)/parts/sun_to_lunar_phases/sun_to_lunar_phases_gear_3.stl
STL_FILES += $(CURDIR)/parts/sun_to_lunar_phases/sun_to_lunar_phases_gear_4.stl
STL_FILES += $(CURDIR)/parts/sun_to_lunar_phases/sun_to_lunar_phases_gear_5.stl
STL_FILES += $(CURDIR)/parts/sun_to_lunar_phases/sun_to_lunar_phases_gear_6.stl
STL_FILES += $(CURDIR)/parts/sun_to_lunar_phases/sun_to_lunar_phases_gear_7.stl

SUN_TO_LUNAR_PHASES_DEPS = $(CURDIR)/utils/constants/sun_to_lunar_phases/env.scad

$(CURDIR)/parts/sun_to_lunar_phases/sun_to_lunar_phases_gear_1.stl: $(SUN_TO_LUNAR_PHASES_DEPS)
$(CURDIR)/parts/sun_to_lunar_phases/sun_to_lunar_phases_gear_2.stl: $(SUN_TO_LUNAR_PHASES_DEPS)
$(CURDIR)/parts/sun_to_lunar_phases/sun_to_lunar_phases_gear_3.stl: $(SUN_TO_LUNAR_PHASES_DEPS)
$(CURDIR)/parts/sun_to_lunar_phases/sun_to_lunar_phases_gear_4.stl: $(SUN_TO_LUNAR_PHASES_DEPS)
$(CURDIR)/parts/sun_to_lunar_phases/sun_to_lunar_phases_gear_5.stl: $(SUN_TO_LUNAR_PHASES_DEPS)
$(CURDIR)/parts/sun_to_lunar_phases/sun_to_lunar_phases_gear_6.stl: $(SUN_TO_LUNAR_PHASES_DEPS)
$(CURDIR)/parts/sun_to_lunar_phases/sun_to_lunar_phases_gear_7.stl: $(SUN_TO_LUNAR_PHASES_DEPS)
