STL_FILES += $(CURDIR)/parts/moon_to_zodiac/moon_to_zodiac_gear_1.stl
STL_FILES += $(CURDIR)/parts/moon_to_zodiac/moon_to_zodiac_gear_2.stl
STL_FILES += $(CURDIR)/parts/moon_to_zodiac/moon_to_zodiac_gear_3.stl
STL_FILES += $(CURDIR)/parts/moon_to_zodiac/moon_to_zodiac_gear_4.stl
STL_FILES += $(CURDIR)/parts/moon_to_zodiac/moon_to_zodiac_gear_5.stl

MOON_TO_ZODIAC_DEPS = $(CURDIR)/utils/constants/moon_to_zodiac/env.scad

$(CURDIR)/parts/moon_to_zodiac/moon_to_zodiac_gear_1.stl: $(MOON_TO_ZODIAC_DEPS)
$(CURDIR)/parts/moon_to_zodiac/moon_to_zodiac_gear_2.stl: $(MOON_TO_ZODIAC_DEPS)
$(CURDIR)/parts/moon_to_zodiac/moon_to_zodiac_gear_3.stl: $(MOON_TO_ZODIAC_DEPS)
$(CURDIR)/parts/moon_to_zodiac/moon_to_zodiac_gear_4.stl: $(MOON_TO_ZODIAC_DEPS)
$(CURDIR)/parts/moon_to_zodiac/moon_to_zodiac_gear_5.stl: $(MOON_TO_ZODIAC_DEPS)
